apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: dynamic-pvc-nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: dynamic-pvc-nfs-for-nginx-pv1
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
