apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-pvc-nfs-for-nginx-pv1
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
