apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxmetallb
spec:
  selector:
    matchLabels:
      app: nginxmetallb
  template:
    metadata:
      labels:
        app: nginxmetallb
    spec:
      containers:
      - name: nginxmetallb
        image: nginx
        ports:
        - name: http
          containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginxmetallb
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginxmetallb
  type: LoadBalancer