all:

  hosts:

  children:

    loadbalancer:
      hosts:
        linux10:
          ansible_host: 40.68.205.136
          ansible_user: adminuser
          ansible_connection: ssh
          ansible_ssh_private_key_file: "{{ansible_ssh_private_key_file_path}}"
    vmmasters:
      hosts:
        linux20:
          ansible_host: 13.81.246.84
          ansible_user: adminuser
          ansible_connection: ssh
          ansible_ssh_private_key_file: "{{ansible_ssh_private_key_file_path}}"
        linux30:
          ansible_host: 13.81.245.10
          ansible_user: adminuser
          ansible_connection: ssh
          ansible_ssh_private_key_file: "{{ansible_ssh_private_key_file_path}}"
        linux40:
          ansible_host: 13.81.247.139
          ansible_user: adminuser
          ansible_connection: ssh
          ansible_ssh_private_key_file: "{{ansible_ssh_private_key_file_path}}"
    vmworkers:
      hosts:
        13.81.247.139:

    vmwindows:
      hosts:
        windows10:
          ansible_host: 51.137.206.42
          ansible_user: adminuser
          ansible_password: Passw@rd1
          ansible_connection: ssh
          ansible_shell_type: cmd
        windows20:
          ansible_host: 51.137.206.54
          ansible_user: adminuser
          ansible_password: Passw@rd1
          ansible_connection: ssh
          ansible_shell_type: cmd



