---
- name: all workers
  become: true
  hosts: vmworkers
  become: true
  roles:
    - allworkers
 
- name: Install NFS server
  hosts: loadbalancer
  become: true
  roles:
    - nfsserver
    - haproxy
    - ansible
#    - nginx



- name: Install NFS clients
  hosts: vmmasters
  become: true
  roles:
    - nfsclients

# ----------------------------------------sakın silmeyin windows swarm için lazım
# - name: Install Windows tools
#   hosts: vmwindows
#   roles:
#     - wintools

# - name: Install Docker
#   hosts: vmwindows
#   roles:
#     - winswarm
#     - wintools



