---
- name: Create Infra
  hosts: localhost
  tasks:
    - include: tasks/create_infra.yml
    - include: tasks/create_infra_linux.yml
#    - include: tasks/create_infra_windows.yml


- name: Create Azure Linux Servers
  hosts: localhost
  tasks:
    - include: tasks/create_linux_servers.yml

# - name: Create Azure Windows Servers
#   hosts: localhost
#   tasks:
#     - include: tasks/create_windows_servers.yml
