version: '3'
services:
    project1:
        image: localhost:5001/aspnet  # docker-compose üzerinden push komutu çalıştrıldığında bu adres image deploy edilecek
        build:
            context: ./project1
            dockerfile: Dockerfile
        ports:
            - "6000:5005"
        environment:
            REDIS_PASSWORD: password123
            ASPNETCORE_ENVIRONMENT: Development
        container_name: aspnet
        depends_on: 
            - project2

    project2:
        image: localhost:5001/redis  # goes to local registry
        build:
            context: ./project2
            dockerfile: Dockerfile
        container_name: redis
        ports:
            - "6379:6379"
        environment:
            REDIS_PASSWORD: password123
    