resource_group_name: rg_kubernetes
virtual_network_name: vn_kubernetes
subnet_name: sn_kubernetes
public_ip_for_lb_name: pip_kubernetes
storage_account_name: sakubernetes2
security_group_name: sgkubernetes2

linux_servers:
  - {name: linux10, objective: "load balancer NFS" , vm_username: adminUser, vm_password: Passw@rd1, network_interface_name: linux1ni, public_ip: True}
  - {name: linux20, objective: "etcd1 master1 worker1", vm_username: adminUser, vm_password: Passw@rd1, network_interface_name: linux2ni, public_ip: False}
  - {name: linux30, objective: "etcd2 master2 worker2", vm_username: adminUser, vm_password: Passw@rd1, network_interface_name: linux3ni, public_ip: False}
  - {name: linux40, objective: "etcd3 master3 worker3", vm_username: adminUser, vm_password: Passw@rd1, network_interface_name: linux4ni, public_ip: False}

# windows_servers:
#  - {name: linux1, objective: "test" , vm_username:administrator, vm_password: Passw@rd1}


