kind: KubeletConfiguration
address: 0.0.0.0
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: "/var/lib/kubernetes/ca.pem"
authorization:
  mode: Webhook
cgroupDriver: systemd
cgroupsPerQOS: true
clusterDNS:
  - "10.32.0.10"
podCIDR: "10.200.0.0/16"
clusterDomain: "cluster.local"
resolvConf: "/run/systemd/resolve/resolv.conf"
rotateCertificates: true
tlsCertFile: "/var/lib/kubelet/worker1.pem"
tlsPrivateKeyFile: "/var/lib/kubelet/worker1-key.pem"
contentType: application/vnd.kubernetes.protobuf
cpuCFSQuota: true
enableControllerAttachDetach: true
enableDebuggingHandlers: true
enforceNodeAllocatable:
  - "pods"
failSwapOn: false
hairpinMode: promiscuous-bridge
healthzBindAddress: 127.0.0.1
healthzPort: 10248
port: 10250
serializeImagePulls: true
staticPodPath: /etc/kubernetes/manifests