- name: Create Public IP for Load Balancer
  azure_rm_publicipaddress:
    resource_group: "{{ resource_group_name }}"
    name: "{{ public_ip_for_lb_name }}"
    allocation_method: Static


- name: Create virtual network inteface with Public IP cards for linux VMs
  azure_rm_networkinterface:
    resource_group: "{{ resource_group_name }}"
    name: "{{ item.network_interface_name }}"
    virtual_network: "{{ virtual_network_name }}"
    subnet: "{{ subnet_name }}"
    security_group_name: "{{ security_group_name }}"
    state: present
    ip_configurations:
      - name: ipconfigs
        primary: True
        public_ip_allocation_method: Static
        public_ip_name: "{{ public_ip_for_lb_name }}"    
  register: vni_result_public_ip
  tags:
    - 4
  with_items: "{{ linux_servers }}"
  when: item.static_public_ip == True


- debug:
    msg: "virtual network inteface with public ip is created for linux. {{ vni_result_public_ip }}"


- name: Create virtual network inteface cards for linux VMs
  azure_rm_networkinterface:
    resource_group: "{{ resource_group_name }}"
    name: "{{ item.network_interface_name }}"
    virtual_network: "{{ virtual_network_name }}"
    subnet: "{{ subnet_name }}"
    security_group_name: "{{ security_group_name }}"
    state: present
    ip_configurations:
      - name: ipconfigs
        primary: True
        public_ip_allocation_method: Dynamic
        public_ip_name: "{{ item.name }}_{{ item.network_interface_name }}"

  register: vni_result
  with_items: "{{ linux_servers }}"
  when: item.static_public_ip == False


- debug:
    msg: "virtual network inteface is created for linux. {{ vni_result }}"


